-- =============================================
-- BASE DE DONNEES : CALENDRIER DES EXAMENS
-- =============================================

CREATE DATABASE IF NOT EXISTS calendrier_examens CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE calendrier_examens;

-- ----------------------------
-- TABLE : professeur
-- ----------------------------
CREATE TABLE professeur (
    id_professeur INT PRIMARY KEY AUTO_INCREMENT,
    nom_professeur VARCHAR(100) NOT NULL
);

-- ----------------------------
-- TABLE : filiere
-- ----------------------------
CREATE TABLE filiere (
    id_filiere INT PRIMARY KEY AUTO_INCREMENT,
    nom_filiere VARCHAR(100) NOT NULL,
    annee TINYINT NOT NULL COMMENT '1=1ère année, 2=2ème année, 3=3ème année',
    CHECK (annee IN (1, 2, 3))
);

-- ----------------------------
-- TABLE : matiere
-- ----------------------------
CREATE TABLE matiere (
    id_matiere INT PRIMARY KEY AUTO_INCREMENT,
    nom_matiere VARCHAR(200) NOT NULL,
    id_professeur INT NOT NULL,
    id_filiere INT NOT NULL,
    jour TINYINT NOT NULL COMMENT '1=Lundi, 2=Mardi, 3=Mercredi, 4=Jeudi, 5=Vendredi, 6=Samedi',
    type_examen VARCHAR(20) NOT NULL COMMENT 'DS=Devoir Surveillé, Examen=Session Principale',
    FOREIGN KEY (id_professeur) REFERENCES professeur(id_professeur),
    FOREIGN KEY (id_filiere) REFERENCES filiere(id_filiere)
);

-- ----------------------------
-- INSERTIONS : professeur
-- ----------------------------
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (1, 'MALEK Jihene');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (2, 'KARMANI Sourour');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (3, 'ELOURAGINI Salem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (4, 'BELHADJ TAHER Ahmed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (5, 'BEN NACEUR Ferdaws');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (6, 'EL MAY Sana');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (7, 'MAHMOUD Rihem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (8, 'KOUKA Neji');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (9, 'SASSI Latifa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (10, 'HENTATI Nesrine');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (11, 'ILJI Samia');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (12, 'MAHMOUDI Nejib');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (13, 'CHOUIGUI Ajmi');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (14, 'BEN SALAH Mohamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (15, 'BEN HAMMADI KACEM Iyadh');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (16, 'HEDHILI Lamia');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (17, 'MABROUK Hanene');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (18, 'BOUFADEN Tarek');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (19, 'SLIMENE Ons');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (20, 'KALLEL Nabil');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (21, 'OUNI Faten');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (22, 'AMMAR Emna');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (23, 'CHEBBI Afef');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (24, 'ZERGANE Amel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (25, 'LEFFET Samia');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (26, 'MAZHOUDA Kamel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (27, 'HATTAB ABROUGUI Hanen');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (28, 'BELGHITH Nader');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (29, 'MOULAHI Samir');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (30, 'BLAYECH Hayfa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (31, 'ABDELKEFI Mahdi');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (32, 'SOUANI Chokri');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (33, 'TARRACH Fredj');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (34, 'TRIKI GARGOUI Dorra');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (35, 'BENNOUR Fadhel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (36, 'SAIDI Faouzi');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (37, 'FOURATI Farah');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (38, 'BEN CHRIFA Ali');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (39, 'ZOUARI Slim');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (40, 'FARHAT Habib');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (41, 'BEN MAKHLOUF Aicha');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (42, 'ZAABOUB Wala');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (43, 'BEN HADJ SALAH Hend');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (44, 'JABLI Nizar');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (45, 'HSAIRI Nizar');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (46, 'BANNOUR Sana');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (47, 'ZAABOUB Nihel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (48, 'HEMAYED Mariem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (49, 'GUESMI Hattab');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (50, 'SAYAHI Ikbel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (51, 'GHOZZI Rim');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (52, 'BANAWAZ Marwa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (53, 'GARNA Tarek');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (54, 'BEN ABDELJELIL Dorra');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (55, 'FRIJA Mounir');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (56, 'BEN SGHAIER Rabii');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (57, 'NAIJA Ahmed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (58, 'MECHI Rachid');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (59, 'DENDEN Mohsen');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (60, 'BAROUNI Yosra');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (61, 'AMMAR Anis');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (62, 'CHEMKHA Hichem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (63, 'FEKI Nabih');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (64, 'HOUIDI Ajmi');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (65, 'BELHADJ MESSOUD Najib');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (66, 'OMMEZINE Anis');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (67, 'ABROUG Anis');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (68, 'MECHRI HoucemEddine');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (69, 'KHALFALLAH Sofiane');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (70, 'BEN SALAH Chokri');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (71, 'BEN KHALIFA Khaled');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (72, 'LAAMOURI Adnene');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (73, 'RADHOUEN Amina');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (74, 'KRIBI Badreddine');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (75, 'BEN ABDELGHANI Farouk');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (76, 'BRAHIM Taoufik');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (77, 'BOUSRIH Ines');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (78, 'HAJJAJI Mohamed Ali');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (79, 'CHOUCHENE Fraj');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (80, 'BRAHEM Maryem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (81, 'ARFAOUI Latifa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (82, 'ZOUAGHI Abderrazak');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (83, 'JMOUR Marwen');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (84, 'ZOUARI Wiem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (85, 'MATHLOUTHI Houda');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (86, 'BRINI Saoussen');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (87, 'ABDALLAH Bouthaina');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (88, 'DHIFLAOUI Hafedh');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (89, 'CHAABANE Haykel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (90, 'BCHIR Mounira');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (91, 'KHELIFA Nour ElHouda');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (92, 'GHABI Chakib');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (93, 'MEMMI Hanene');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (94, 'MILED Mariem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (95, 'GASSAB Sirine');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (96, 'FATNASSI Ons');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (97, 'BOUHAJEB Houcine');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (98, 'CHIBANI Radhia');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (99, 'HAMOUDA Mahmoud');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (100, 'HADJ KACEM Mouna');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (101, 'MAZZOUZ Souha');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (102, 'GAFSI Mohamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (103, 'TRABELSI Ramzi');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (104, 'BAWEB BHOURI Ines');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (105, 'KHEDHER Atef');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (106, 'KORTAS Salem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (107, 'BEN ABID Nabiha');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (108, 'BEN AHMED Ikram');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (109, 'KHALIL Makram');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (110, 'BEN FREDJ Hana');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (111, 'CHAIEB Salwa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (112, 'BEN AHMED Sofiene');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (113, 'AMMAR Ahlem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (114, 'FARJALLAH Mohamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (115, 'GUERFEL Mohamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (116, 'ABDELGHANI Maher');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (117, 'BELHADJ Rachida');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (118, 'JDAY Rim');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (119, 'MELLOULI MOALLA Dorra');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (120, 'GARRAB Hatem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (121, 'KHOUAJA Anis');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (122, 'HAMDI Belgacem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (123, 'TAHRI Randa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (124, 'HLEL Dalel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (125, 'TAAMALLAH Aroua');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (126, 'ZOUAOUI Safa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (127, 'FETOUI Mourad');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (128, 'ZRIBI Temim');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (129, 'HICHRI Heithem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (130, 'JAOUADI Ines');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (131, 'BEN SALEM Manel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (132, 'BOUKADIDA Hatem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (133, 'ALKAMEL Foued');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (134, 'MALLEK Hanen');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (135, 'HAMROUNI Fakher');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (136, 'HADDAD Omar');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (137, 'BEN SALAH Tarek');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (138, 'SAIDANE Mhamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (139, 'ZBIDI JAMEL Wafa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (140, 'BEN AICHA Anissa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (141, 'SABRI Houssem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (142, 'JALLALI Faycal');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (143, 'BEN SLIMANE Ichrak');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (144, 'AYDI Maha');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (145, 'WALI Wafa');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (146, 'WALHAZI Hajer');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (147, 'SOUISSI Werda Imen');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (148, 'BEN NJIMA Chayma');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (149, 'MAZGAR Akram');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (150, 'MALKI Wahid');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (151, 'ZAAFRANE Yosr');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (152, 'BOUDOKHANE Imene');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (153, 'EL GHARBI Ramzi');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (154, 'GHOURABI Yosra Maha');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (155, 'TAGORTI Mohamed Ali');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (156, 'BAHLOUL Riadh');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (157, 'BDIRI GABBOUJ Houda');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (158, 'TOUNSI Mohamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (159, 'MAHFOUDHI Alkamel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (160, 'TRIMECH GHDIRA Elhem');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (161, 'HASSINE Hela');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (162, 'OUNI Jalel');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (163, 'SAADANI Asma');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (164, 'MDALLA Mohamed');
INSERT INTO professeur (id_professeur, nom_professeur) VALUES (165, 'GAIED Refka');

-- ----------------------------
-- INSERTIONS : filiere
-- ----------------------------
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (1, 'Licence ISI', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (2, 'Licence SI', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (3, 'Licence EEA', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (4, 'Licence GM', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (5, 'Licence EM', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (6, 'Licence GC', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (7, 'Licence Eng', 1);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (8, 'Licence EEA-AII', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (9, 'Licence EEA-EI', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (10, 'Licence EEA-SE', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (11, 'Licence GM-CPI', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (12, 'Licence EM-MA', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (13, 'Licence EM-MI', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (14, 'Licence GC-BAT', 3);
INSERT INTO filiere (id_filiere, nom_filiere, annee) VALUES (15, 'Licence GC-PC', 3);

-- ----------------------------
-- INSERTIONS : matiere
-- ----------------------------
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (1, 'Systèmes Logiques', 1, 1, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (2, 'Systèmes Logiques & Architecture des ordinateurs', 2, 2, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (3, 'Mécanique', 3, 3, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (4, 'Procédés 1', 4, 4, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (5, 'Algorithmique et programmation', 5, 5, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (6, 'Algorithmique et programmation', 5, 6, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (7, 'Outil de calcul en énergétique', 6, 7, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (8, 'Système d''exploitation 1', 7, 1, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (9, 'Système d''exploitation 1', 7, 2, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (10, 'Systèmes d''exploitation', 8, 3, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (11, 'Mécanique 1', 9, 4, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (12, 'Technologie de construction', 10, 5, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (13, 'Mécanique générale', 9, 6, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (14, 'Outil numérique', 11, 7, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (15, 'Analyse 1', 12, 1, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (16, 'Analyse 1', 13, 2, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (17, 'Analyse 1', 14, 3, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (18, 'Analyse 1', 15, 4, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (19, 'Analyse 1', 16, 5, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (20, 'Analyse 1', 13, 6, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (21, 'Analyse 1', 17, 7, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (22, 'Propagation et rayonnement', 18, 1, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (23, 'Technologies Multimédias', 19, 2, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (24, 'Electrostatique et Magnétostatique', 20, 3, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (25, 'Electrotechnique', 21, 4, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (26, 'Initiation à la programmation', 22, 5, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (27, 'Mécanique des fluides', 23, 6, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (28, 'Electrostatique & Magnétostatique', 18, 7, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (29, 'Algèbre 1', 24, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (30, 'Algèbre 1', 25, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (31, 'Algèbre 1', 26, 3, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (32, 'Algèbre 1', 15, 4, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (33, 'Algèbre 1', 27, 5, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (34, 'Algebre 1', 28, 6, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (35, 'Algèbre 1', 29, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (36, 'Atelier Programmation 1', 30, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (37, 'Atelier programmation 1', 31, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (38, 'Electronique Numérique', 32, 3, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (39, 'Electronique', 33, 4, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (40, 'Électronique appliquée', 34, 5, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (41, 'Electro-magnétostatique et optique', 35, 6, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (42, 'Introduction à la thermodynamique', 35, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (43, 'Electricité Electronique', 36, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (44, 'Logique formelle', 37, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (45, 'Circuits Electriques', 38, 3, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (46, 'Conception 1', 39, 4, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (47, 'Outils de communication graphiques', 39, 5, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (48, 'Conduction & Convection', 40, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (49, 'Algorithmique et structure des données', 30, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (50, 'Algorithmique et structure de données', 41, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (51, 'Algorithmique et Programmation', 42, 3, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (52, 'Science des matériaux 1', 43, 4, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (53, 'Circuits électriques', 44, 5, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (54, 'Topographie et cartographie', 45, 6, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (55, 'Ressources énergétiques', 46, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (56, 'Atelier de programmation', 47, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (57, 'Lecture des plans', 48, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (58, 'Systèmes temps réel', 49, 1, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (59, 'Virtualisation et Cloud', 50, 2, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (60, 'Chaine d''acquisition et de commande', 51, 8, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (61, 'Schémas électriques', 52, 9, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (62, 'Technologie des Capteurs', 53, 10, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (63, 'Analyse fonctionnelle', 54, 11, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (64, 'Diagnostique automobiles', 55, 12, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (65, 'Gestion de la maintenance', 56, 13, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (66, 'Mise en situation et prise de décision 2: Sécurité incendie', 57, 14, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (67, 'Procédés généraux de construction+Visites de chantier', 57, 15, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (68, 'Energies renouvelable', 58, 7, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (69, 'Cloud et Virtualisation', 59, 1, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (70, 'Sécurité informatique', 60, 2, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (71, 'Domotique', 61, 8, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (72, 'Programmation de Raspberry Pi en Python', 61, 9, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (73, 'Hyperfréquence', 62, 10, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (74, 'Analyse vibratoire et diagnostic', 63, 11, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (75, 'Architecture et Dynamique des véhicules', 64, 12, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (76, 'Schéma et Maintenances des équipements électromécaniques', 65, 13, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (77, 'Electricité du bâtiment', 66, 14, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (78, 'Ouvrages spéciaux', 67, 15, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (79, 'Maîtrise de l''énergie', 68, 7, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (80, 'Big Data', 69, 1, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (81, 'Développement d''applications réparties', 69, 2, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (82, 'Energies Renouvelables', 70, 8, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (83, 'Energies renouvelables', 70, 9, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (84, 'Conception haut niveau des systèmes embarqués', 71, 10, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (85, 'Tenue en service des matériaux', 72, 11, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (86, 'Conditionnement automobile', 73, 12, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (87, 'Introduction à la robotique', 74, 13, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (88, 'VRD', 75, 14, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (89, 'VRD', 23, 15, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (90, 'Machines Frigorifiques', 76, 7, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (91, 'IA et Machine learning', 49, 1, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (92, 'Framework et technologies Big Data', 77, 2, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (93, 'Instrumentation LabVIEW', 78, 8, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (94, 'Labview', 78, 9, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (95, 'Effets Thermiques dans les composants', 79, 10, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (96, 'FAO', 80, 11, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (97, 'CAO/FAO', 81, 12, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (98, 'CAO/FAO', 80, 13, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (99, 'Equipements techniques des bâtiments', 82, 14, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (100, 'Aménagement des routes', 83, 15, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (101, 'Régulation des systèmes énergétiques', 46, 7, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (102, 'Réseaux industriels', 84, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (103, 'ERP et intégration des Systèmes d''information', 84, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (104, 'Régulation Industrielle', 85, 8, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (105, 'Production et distribution de l''énergie électrique', 86, 9, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (106, 'Systèmes embarqués temps réel', 87, 10, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (107, 'Mécanique des solides élastiques', 88, 11, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (108, 'Electroniques embarquées pour automobiles', 89, 12, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (109, 'Systèmes embarqués', 90, 13, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (110, 'Organisation et planification des chantiers', 91, 14, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (111, 'Ouvrages d''art 2', 91, 15, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (112, 'Froid industriel', 92, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (113, 'Entreprenariat', 93, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (114, 'Entrepreunariat', 93, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (115, 'Création d''Entreprise', 94, 8, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (116, 'Création d''Entreprise', 94, 9, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (117, 'Création d''Entreprise', 94, 10, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (118, 'Soft Skills', 95, 11, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (119, 'Création d''entreprise', 94, 12, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (120, 'Création d''entreprise', 96, 13, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (121, 'Creation et gestion d''entreprise', 94, 14, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (122, 'Creation et gestion d''entreprise', 94, 15, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (123, 'Création d''entreprise', 97, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (124, 'Technologie des Réseaux sans fil pour l''IoT', 59, 1, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (125, 'Architecture SOA et services web', 31, 2, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (126, 'Modélisation et commande dans l''espace d''états', 98, 8, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (127, 'Convertisseurs de puissance et qualité de l''énergie', 99, 9, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (128, 'Electronique de puissance 2', 99, 10, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (129, 'CAO', 100, 11, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (130, 'Procédés généraux de construction+ visite des chantiers', 82, 14, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (131, 'Conception et calcul des routes 2', 45, 15, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (132, 'Centrale de traitement d''air', 101, 7, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (133, 'Electronique programmable (VHDL,FPGA)', 102, 8, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (134, 'Commande des machines', 103, 9, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (135, 'Instrumentation LabVIEW', 102, 10, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (136, 'Hydraulique de bâtiment', 75, 14, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (137, 'Ouvrages hydrauliques', 75, 15, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (138, 'Equipements Fluidiques', 104, 7, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (139, 'Automates programmables et Supervision', 105, 8, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (140, 'Machines thermiques', 106, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (141, 'Conception des systèmes numériques (Co-design)', 107, 1, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (142, 'Machine Learning', 108, 2, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (143, 'Dimensionnement des machines électriques', 109, 9, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (144, 'Systèmes de vision embarqués', 110, 10, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (145, 'Diagnostic des systèmes de climatisation', 76, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (146, 'Sécurité IoT', 111, 1, 6, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (147, 'Calcul Haute performance', 112, 1, 6, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (148, 'Préparation à l''environnement professionnel', 97, 2, 6, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (149, 'comptabilité énergétique', 106, 7, 6, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (150, 'Programmation orientée objet', 37, 1, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (151, 'Paradigme de programmation orientée objet', 113, 2, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (152, 'Instrumentation et Métrologie', 114, 8, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (153, 'Instrumentation et Métrologie', 114, 9, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (154, 'Traitement du signal Analogique', 115, 10, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (155, 'Mécanique 3', 116, 11, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (156, 'Mécanique des systèmes', 39, 12, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (157, 'Mécanique des systèmes', 39, 13, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (158, 'Calcul des structures', 117, 14, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (159, 'Calcul des structures', 117, 15, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (160, 'Les capteurs', 114, 7, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (161, 'Probabilité Statistique', 118, 1, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (162, 'Probabilité et statistique', 118, 2, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (163, 'Fonctions d''Electronique Analogique', 119, 8, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (164, 'Fonctions d''Electronique Analogique', 119, 9, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (165, 'Fonctions d''Electronique Analogique', 120, 10, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (166, 'Régulation et asservissement', 121, 11, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (167, 'Fonctions électronique analogiques', 122, 12, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (168, 'Fonctions électronique analogiques', 122, 13, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (169, 'Probabilité et statistique', 123, 14, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (170, 'Probabilité et statistique', 123, 15, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (171, 'Circuits Electriques', 124, 7, 1, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (172, 'Programmation Python', 22, 1, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (173, 'Cryptographie', 125, 2, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (174, 'Transmission des données', 34, 8, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (175, 'Transmission des Données', 126, 9, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (176, 'Instrumentation et Métrologie', 127, 10, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (177, 'Méthodes de fabrication par usinage', 74, 11, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (178, 'Techniques de production par usinage', 128, 12, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (179, 'Techniques de production par usinage', 129, 13, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (180, 'Construction durable et éco-matériaux', 130, 14, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (181, 'Construction durable et éco-matériaux', 130, 15, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (182, 'Théorie de la mesure et Traitement informatique', 127, 7, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (183, 'Technologies Multimédia', 50, 1, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (184, 'Théorie des langages et des Automates', 131, 2, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (185, 'Conception des cartes électronique', 132, 8, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (186, 'Réseaux électriques et transformateurs 1', 21, 9, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (187, 'Diagnostic et maintenance des systèmes électroniques', 133, 10, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (188, 'Mécanique des Fluides', 73, 11, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (189, 'Dynamique des solides rigides', 134, 12, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (190, 'Dynamique des solides rigides', 134, 13, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (191, 'Mécanique des sols', 135, 14, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (192, 'Mécanique des sols', 135, 15, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (193, 'Dynamique des fluides', 73, 7, 2, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (194, 'Réseaux Locaux', 60, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (195, 'Ingénierie des Bases de Données', 136, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (196, 'Architecture des Microprocesseurs et Microcontrôleurs', 132, 8, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (197, 'Architecture des Microprocesseurs et Microcontrôleurs', 132, 9, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (198, 'Architecture des Microprocesseurs et Microcontrôleurs', 137, 10, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (199, 'Thermique industrielle', 58, 11, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (200, 'Fonctions électroniques numériques', 89, 12, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (201, 'Fonctions électroniques numériques', 89, 13, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (202, 'Outils mathématiques', 15, 14, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (203, 'Outils mathématiques', 15, 15, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (204, 'Thermique du batiment', 40, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (205, 'Automate', 85, 1, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (206, 'Conception des Systèmes d''Information', 138, 2, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (207, 'Automatique', 121, 8, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (208, 'Automatique', 70, 9, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (209, 'Automatique', 139, 10, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (210, 'Automatismes industriels', 140, 11, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (211, 'Automatisme Industriels', 85, 12, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (212, 'Automatisme Industriels', 140, 13, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (213, 'Béton armé', 130, 14, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (214, 'Béton armé', 130, 15, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (215, 'Installations de climatisation', 6, 7, 3, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (216, 'Graphes et optimisation', 141, 1, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (217, 'Graphes et optimisation', 141, 2, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (218, 'Diagnostic et maintenance des systèmes électroniques', 90, 8, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (219, 'Electronique de puissance 1', 52, 9, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (220, 'Transmission des Données', 62, 10, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (221, 'Procédés d''obtention des pièces brutes', 74, 11, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (222, 'Procédés d''obtention des pièces brutes', 4, 12, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (223, 'Procédés d''obtention des pièces brutes', 4, 13, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (224, 'Engins et matériels', 82, 14, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (225, 'Engins et matériels', 82, 15, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (226, 'Machines électriques', 142, 7, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (227, 'Gestion d''entreprise', 143, 1, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (228, 'Gestion d''entreprise', 143, 2, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (229, 'Gestion d''Entreprise', 144, 8, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (230, 'Gestion d''Entreprise', 144, 9, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (231, 'Gestion d''Entreprise', 144, 10, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (232, 'Culture d''entreprise', 144, 11, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (233, 'Culture entrepreneuriale', 96, 12, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (234, 'Culture entrepreneuriale', 144, 13, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (235, 'Culture entrepreneuriale', 96, 14, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (236, 'Culture entrepreneuriale', 143, 15, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (237, 'Normes et qualités', 46, 7, 4, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (238, 'Méthodologie de Conception de logiciel', 145, 1, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (239, 'Programmation Java', 146, 2, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (240, 'Traitement du signal Analogique', 139, 8, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (241, 'Traitement du signal Analogique', 139, 9, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (242, 'Régulation et asservissement', 70, 12, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (243, 'Régulation et asservissement', 70, 13, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (244, 'Hydraulique urbaine et Hydrologie', 75, 14, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (245, 'Hydraulique urbaine et Hydrologie', 75, 15, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (246, 'Rayonnement thermique', 58, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (247, 'Architectures Avancées des Processeurs', 147, 1, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (248, 'Thermochimie de la Combustion', 76, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (249, 'Fondements des Bases de données', 148, 1, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (250, 'Installations de chauffage', 6, 7, 5, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (251, 'Schémas électriques appliqués aux systèmes HVAC', 149, 7, 6, 'DS');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (252, 'Anglais 3', 150, 1, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (253, 'Anglais 3', 151, 2, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (254, 'Anglais', 152, 8, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (255, 'Anglais', 152, 9, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (256, 'Anglais', 152, 10, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (257, 'Anglais 3', 150, 11, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (258, 'Anglais 3', 153, 12, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (259, 'Anglais 3', 152, 13, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (260, 'Anglais III', 154, 14, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (261, 'Anglais', 154, 15, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (262, 'Anglais III', 150, 7, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (263, 'Hydraulique urbaine et Hydrologie', 155, 14, 4, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (264, 'CAO et PCB', 142, 10, 5, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (265, 'Conception 3', 156, 11, 5, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (266, 'Soft skills', 93, 7, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (267, 'Systèmes Logiques', 157, 1, 2, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (268, 'Technologie de construction', 158, 5, 2, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (269, 'Analyse 1', 159, 3, 2, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (270, 'Techniques de communication 1', 160, 1, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (271, 'Techniques de communication 1', 160, 2, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (272, 'Techniques de communication I', 161, 7, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (273, 'Anglais 1', 150, 1, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (274, 'Anglais 1', 162, 2, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (275, 'Anglais', 154, 3, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (276, 'Anglais 1', 150, 4, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (277, 'Anglais 1', 152, 5, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (278, 'Anglais I', 163, 6, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (279, 'Anglais I', 154, 7, 3, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (280, 'Culture et Compétences Numériques 1', 48, 4, 5, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (281, 'Culture et compétences numériques', 164, 6, 5, 'Examen');
INSERT INTO matiere (id_matiere, nom_matiere, id_professeur, id_filiere, jour, type_examen) VALUES (282, 'Culture et Compétences numérique', 165, 7, 5, 'Examen');
