version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: OR_google_database
      MYSQL_USER: exam_user
      MYSQL_PASSWORD: exam_password
    ports:
      - "3307:3306" # Use a different port if needed, 3306 might be busy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80" # Interface web de phpMyAdmin locale
    depends_on:
      - db
    restart: always
